import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/hooks/useAuth";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
const inter = Geist({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Subs app",
  description: "Generated by subs app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <AuthProvider>
          {children}
          <Toaster className="text-gray-800" />
        </AuthProvider>
      </body>
    </html>
  );
}
