import { AuthProvider } from "@/hooks/useAuth";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
const inter = Geist({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Subs app",
  description: "Generated by subs app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased `}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          <Toaster
            position="bottom-right"
            reverseOrder={false}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
